version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3005:3005"
    environment: 
      - S3_CREDS
      - SMTP_CREDS
    volumes: 
      - .:/usr/src/app
    depends_on:
      - "mysql"
  
  mysql:
    image: "mysql:5"
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
