version: '3'
services:
  unit-test:
    build: 
      context: .
      dockerfile: ./test.Dockerfile
    environment: 
      - S3_CREDS
      - SMTP_CREDS
      - user
    volumes: 
      - .:/usr/src/app 

   